{{- $iterations := .Values.iterations | int -}}
{{- range $index0 := untilStep 1 (int $iterations) 1 }}
---
apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: HeaderManipulationPolicy
metadata:
  name: modify-header-hsts
  name: ns-{{ $index0 }}
spec:
  applyToRoutes:
  - route:
      labels:
        soa.solo.com/route-table: top-level
  config:
    appendRequestHeaders:
      x-custom-request: bookinfo
    appendResponseHeaders:
      strict-transport-security: max-age=16070400; includeSubDomains
      x-content-type-options: nosniff
      x-frame-options: deny
      x-custom-response: bookinfo
    removeRequestHeaders:
      - user-agent
    removeResponseHeaders:
      - x-server
      - x-envoy-upstream-service-time
{{- end }}