{{- $iterations := .Values.iterations | int -}}
{{- range $index0 := untilStep 1 (int $iterations) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: app-{{ $index0 }}
  namespace: ns-{{ $index0 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8083
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: app-{{ $index0 }}
{{- end }}