{{- $iterations := .Values.iterations | int -}}
{{- range $index0 := untilStep 1 (int $iterations) 1 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-{{ $index0 }}
  namespace: app-{{ $index0 }}
{{- end }}