{{- $iterations := .Values.iterations | int -}}
{{- range $index0 := untilStep 1 (int $iterations) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: service-{{ $index0 }}
  namespace: ns-{{ $index0 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: app-{{ $index0 }}
---
{{- end }}