{{- range .Values.accessPolicies }}
apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  namespace: gloo-mesh
  name: {{ .name }}
spec:
  {{- if .sourceServiceAccounts }}
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
      {{- range .sourceServiceAccounts}}
        - name: {{ .name }}
          namespace: {{ .namespace }}
          clusterName: {{ .clusterName }}
      {{- end }}
  {{- end }}
  {{- if .destinationServices }}
  destinationSelector:
  {{- range .destinationServices }}
  {{- if .match }}
  {{- if or (.match.namespaces) (.match.labels) (.match.clusters) }}
  - kubeServiceMatcher:
      {{- if .match.namespaces }}
      namespaces:
      {{- range .match.namespaces }}
      - {{ . }}
      {{- end}}
      {{- end}}
      {{- if .match.labels }}
      labels:
{{ .match.labels | toYaml | indent 8}}
      {{- end }}
      {{- if .match.clusters }}
      clusters:
      {{- range .match.clusters }}
      - {{ . }}
      {{- end}}
      {{- end}}
  {{- end }}
  {{- end }}
  {{- if .exact }}
  - kubeServiceRefs:
    - services:
        name: {{ .exact.name }}
        namespace: {{ .exact.namespace }}
        cluster:  {{ .exact.cluster }}
  {{- end }}
  {{- end }}
  {{- end }}
---
{{- end }}