{{- range .Values.gateways }}
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualGateway
metadata:
  name: {{ .name }}
  namespace: gloo-mesh
spec:
  ingressGatewaySelectors:
  - portName: {{ .portName }}
    destinationSelectors:
    {{- range .selectors}}
    {{- if .exact }}
    - kubeServiceRefs:
      - services:
          name: {{ .exact.name }}
          namespace: {{ .exact.namespace }}
          clusterName:  {{ .exact.cluster }}
    {{- end }}
    {{- if .match }}
    {{- if or (.match.namespaces) (.match.labels) (.match.clusters) }}
    - kubeServiceMatcher:
        {{- if .match.namespaces }}
        namespaces:
        {{- range .match.namespaces }}
        - {{ . }}
        {{- end}}
        {{- end}}
        {{- if .match.labels }}
        labels:
  {{ .match.labels | toYaml | indent 8}}
        {{- end }}
        {{- if .match.clusters }}
        clusters:
        {{- range .match.clusters }}
        - {{ . }}
        {{- end}}
        {{- end}}
    {{- end }}
    {{- end }}
    {{- end }}
  connectionHandlers:
  - http:
      routeConfig:
      {{- range .hosts }}
      - virtualHost:
          domains:
          {{- range .domains }}
          - {{ . | quote }}
          {{- end }}
          routes:
          {{- range .match }}
          - routeAction:
              destinations:
{{ .destinations | toYaml | indent 16}}
            {{- if .matches }}
            matchers:
{{ .matches | toYaml | indent 14}}
            {{- end }}
          {{- end }}
      {{- end }}
---
{{- end }}