{{- range .Values.trafficPolicies }}
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  name: {{ .name }}
  namespace: gloo-mesh
spec:
  {{- if .sourceServices }}
  sourceSelector:
  {{- range .sourceServices }}
    {{- if .match }}
    {{- if or (.match.namespaces) (.match.labels) (.match.clusters) }}
    - kubeWorkloadMatcher:
        {{- if .match.namespaces }}
        namespaces:
        {{- range .match.namespaces }}
        - {{ . }}
        {{- end}}
        {{- end}}
        {{- if .match.labels }}
        labels:
  {{ .match.labels | toYaml | indent 8}}
        {{- end }}
        {{- if .match.clusters }}
        clusters:
        {{- range .match.clusters }}
        - {{ . }}
        {{- end}}
        {{- end}}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if .destinationServices }}
  destinationSelector:
  {{- range .destinationServices }}
   {{- if .exact }}
    - kubeServiceRefs:
        services:
        - name: {{ .exact.name }}
          namespace: {{ .exact.namespace }}
          clusterName:  {{ .exact.cluster }}
    {{- end }}
    {{- if .match }}
    {{- if or (.match.namespaces) (.match.labels) (.match.clusters) }}
    - kubeServiceMatcher:
        {{- if .match.namespaces }}
        namespaces:
        {{- range .match.namespaces }}
        - {{ . }}
        {{- end}}
        {{- end}}
        {{- if .match.labels }}
        labels:
  {{ .match.labels | toYaml | indent 8}}
        {{- end }}
        {{- if .match.clusters }}
        clusters:
        {{- range .match.clusters }}
        - {{ . }}
        {{- end}}
        {{- end}}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
  policy:
    {{- if .trafficShiftTo }}
    trafficShift:
      destinations:
{{ .trafficShiftTo | toYaml | indent 8}}
    {{- end }}
---
{{- end }}