{{- range .Values.virtualDestinations }}
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualDestination
metadata:
  name: {{ .name }}
  namespace: gloo-mesh
spec:
  hostname: {{ .hostname | default (printf "%s.global" .name) }}
  port:
    number: {{ .inboundPort }}
    protocol: {{ .protocol }}
    targetName: {{ .backingServices.portName }}
  localized:
    {{- with .failover}}
    failoverDirectives:
{{ . | toYaml | indent 4}}
    {{- end }}
    {{- with .outlierDetection}}
    outlierDetection:
      consecutiveErrors: {{ .consecutiveErrors}}
      interval: {{ .interval}}
      baseEjectionTime: {{ .baseEjectionTime}}
      maxEjectionPercent: {{ .maxEjectionPercent}}
    {{- end }}
    destinationSelectors:
    {{- range .backingServices.selector }}
    {{- if .exact }}
    - kubeServiceRefs:
      - services:
          name: {{ .exact.name }}
          namespace: {{ .exact.namespace }}
          cluster:  {{ .exact.cluster }}
    {{- end }}
    {{- if .match }}
    {{- if or (.match.namespaces) (.match.labels) (.match.clusters) }}
    - kubeServiceMatcher:
        {{- if .match.namespaces }}
        namespaces:
        {{- range .match.namespaces }}
        - {{ . }}
        {{- end}}
        {{- end}}
        {{- if .match.labels }}
        labels:
  {{ .match.labels | toYaml | indent 8}}
        {{- end }}
        {{- if .match.clusters }}
        clusters:
        {{- range .match.clusters }}
        - {{ . }}
        {{- end}}
        {{- end}}
    {{- end }}
    {{- end }}
    {{- end }}
  virtualMesh:
    name: {{ $.Values.virtualMesh.name }}
    namespace: gloo-mesh
---
{{- end }}