{{- if .Values.virtualMesh.enabled }}
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: {{ .Values.virtualMesh.name | default "virtual-mesh" }}
  namespace: gloo-mesh
spec:
  {{- if .Values.virtualMesh.global.defaultDenyAccessPolicy }}
  globalAccessPolicy: ENABLED
  {{- end }}
  federation:
    selectors:
      - {}
  {{- if .Values.virtualMesh.global.tcpKeepAlive.enabled }}
    tcpKeepalive:
      time: {{ .Values.virtualMesh.global.tcpKeepAlive.time }}
      interval: {{ .Values.virtualMesh.global.tcpKeepAlive.interval }}
  {{- end }}
    ingressGatewaySelectors:
{{- with .Values.virtualMesh.eastwestGatewaySelector }}
    - portName: {{ .portName }}
      destinationSelectors:
      - kubeServiceMatcher:
          labels:
{{ .labels | toYaml | indent 12}}
          namespaces:
          {{- range .namespaces }}
          - {{ . }}
          {{- end }}
{{- end }}
  mtlsConfig:
    autoRestartPods: {{ .Values.virtualMesh.certificateManagement.istioCACerts.autoRestartPods }}
    shared:
      rootCertificateAuthority:
      {{- if .Values.virtualMesh.certificateManagement.istioCACerts.autoGenerated }}
        generated: {}
      {{- else }}
        secret:
          name: {{ .Values.virtualMesh.certificateManagement.istioCACerts.customCASecretName }}
          namespace: gloo-mesh
      {{- end }}
  meshes:
{{- range .Values.clusters }}
    - name: istiod-istio-system-{{ .name }}
      namespace: gloo-mesh
{{- end }}
---
{{- end }}